/**
 * @todaypool/design-system
 *
 * Professional design system with comprehensive tokens and theme support.
 * Everything needed to build beautiful, consistent UIs across all platforms.
 */

// Design Tokens
export { colors, type ColorToken, type ColorKey } from './tokens/colors';
export {
  typography,
  textStyles,
  type TypographyToken,
  type TextStyle,
} from './tokens/typography';
export {
  spacing,
  zIndex,
  type SpacingToken,
  type SpacingKey,
  type ZIndexToken,
} from './tokens/spacing';
export {
  shadows,
  elevation,
  type ShadowToken,
  type ElevationToken,
} from './tokens/shadows';
export {
  duration,
  easing,
  transition,
  keyframes,
  animation,
  reducedMotion,
  type DurationToken,
  type EasingToken,
  type TransitionToken,
  type KeyframesToken,
  type AnimationToken,
} from './tokens/animations';
export {
  radius,
  componentRadius,
  platformRadius,
  type RadiusToken,
  type ComponentRadiusToken,
  type PlatformRadiusToken,
} from './tokens/radius';

// Theme System
export {
  ThemeProvider,
  useTheme,
  useColorScheme,
  useColors,
  useDesignTokens,
  getSystemColorScheme,
  resolveColorScheme,
  getResolvedColors,
  createTheme,
  getShadows,
  saveColorScheme,
  loadColorScheme,
  watchSystemColorScheme,
  generateCSSVariables,
  type ColorScheme,
  type Theme,
  type ResolvedColors,
  type ThemeConfig,
  type ThemeContextValue,
} from './theme';

/**
 * Complete Design Token Bundle
 * All tokens in one convenient object
 */
import { colors } from './tokens/colors';
import { typography, textStyles } from './tokens/typography';
import { spacing, zIndex } from './tokens/spacing';
import { shadows, elevation } from './tokens/shadows';
import { duration, easing, transition, animation } from './tokens/animations';
import { radius, componentRadius } from './tokens/radius';

export const tokens = {
  colors,
  typography,
  textStyles,
  spacing,
  zIndex,
  shadows,
  elevation,
  duration,
  easing,
  transition,
  animation,
  radius,
  componentRadius,
} as const;

export type DesignTokens = typeof tokens;

// Components
export {
  Button,
  Input,
  Card,
  CardHeader,
  CardContent,
  CardFooter,
  Badge,
  Modal,
  ModalHeader,
  ModalFooter,
  ToastProvider,
  useToast,
  Toggle,
  Textarea,
  Avatar,
  AvatarGroup,
  Checkbox,
  Spinner,
  FullPageSpinner,
  Tooltip,
  Alert,
  LinearProgress,
  CircularProgress,
  Skeleton,
  SkeletonGroup,
  ProposalCardSkeleton,
  Divider,
  Select,
  Radio,
  RadioGroup,
  Tabs,
  TabPanel,
  Accordion,
  Menu,
  DatePicker,
  InputModal,
  SwipeableCard,
  VoiceInput,
  FAB,
  PullToRefresh,
  NetworkStatus,
  InstallPrompt,
  PageTransition,
  MobilePageTransition,
  FadePageTransition,
  ModalPageTransition,
  ErrorBoundary,
  useAsyncErrorBoundary,
  OfflineQueueIndicator,
  PushPermissions,
  canUsePushNotifications,
  getNotificationPermission,
  requestNotificationPermission,
  CameraUpload,
  canUseCamera,
  getAvailableCameras,
  Onboarding,
  defaultOnboardingSteps,
  saveOnboardingComplete,
  hasCompletedOnboarding,
  clearOnboardingState,
  RatingPrompt,
  RatingPromptManager,
  createRatingPromptManager,
  GestureTutorial,
  defaultGestureTutorialSteps,
  saveGestureTutorialComplete,
  hasCompletedGestureTutorial,
  clearGestureTutorialState,
  type ButtonProps,
  type ButtonVariant,
  type ButtonSize,
  type InputProps,
  type InputSize,
  type CardProps,
  type CardVariant,
  type CardPadding,
  type CardHeaderProps,
  type CardContentProps,
  type CardFooterProps,
  type BadgeProps,
  type BadgeVariant,
  type BadgeSize,
  type BadgeShape,
  type ModalProps,
  type ModalSize,
  type ModalHeaderProps,
  type ModalFooterProps,
  type Toast,
  type ToastVariant,
  type ToastPosition,
  type ToastProviderProps,
  type ToggleProps,
  type ToggleSize,
  type TextareaProps,
  type AvatarProps,
  type AvatarSize,
  type AvatarStatus,
  type AvatarGroupProps,
  type CheckboxProps,
  type CheckboxSize,
  type SpinnerProps,
  type SpinnerSize,
  type SpinnerVariant,
  type FullPageSpinnerProps,
  type TooltipProps,
  type TooltipPosition,
  type AlertProps,
  type AlertVariant,
  type LinearProgressProps,
  type CircularProgressProps,
  type ProgressVariant,
  type ProgressSize,
  type SkeletonProps,
  type SkeletonVariant,
  type SkeletonGroupProps,
  type ProposalCardSkeletonProps,
  type DividerProps,
  type DividerOrientation,
  type DividerVariant,
  type SelectProps,
  type SelectOption,
  type SelectSize,
  type RadioProps,
  type RadioSize,
  type RadioGroupProps,
  type TabsProps,
  type TabsVariant,
  type TabsSize,
  type TabItem,
  type TabPanelProps,
  type AccordionProps,
  type AccordionItem,
  type MenuProps,
  type MenuItem,
  type DatePickerProps,
  type DateShortcut,
  type InputModalProps,
  type SwipeableCardProps,
  type SwipeAction,
  type VoiceInputProps,
  type FABProps,
  type FABAction,
  type PullToRefreshProps,
  type NetworkStatusProps,
  type InstallPromptProps,
  type PageTransitionProps,
  type PageTransitionType,
  type ErrorBoundaryProps,
  type OfflineQueueIndicatorProps,
  type QueuedAction,
  type PushPermissionsProps,
  type PermissionState,
  type CameraUploadProps,
  type OnboardingProps,
  type OnboardingStep,
  type RatingPromptProps,
  type RatingPromptManagerOptions,
  type GestureTutorialProps,
  type GestureTutorialStep,
} from './components';

// Utility Hooks
export {
  useMediaQuery,
  useIsMobile,
  useIsTablet,
  useIsDesktop,
  breakpoints,
  useOnClickOutside,
  useLocalStorage,
  useDebounce,
  useDebouncedCallback,
  useWindowSize,
  useKeyPress,
  useKeyPressEvent,
  useCopyToClipboard,
  useToggle,
  usePrevious,
  useInterval,
  useTimeout,
  useOptimistic,
  useOptimisticValue,
  useShare,
  canShare,
  canShareData,
  useBackgroundSync,
  canBackgroundSync,
  useBadge,
  canUseBadge,
  setBadgeCount,
  clearBadgeCount,
  useIndexedDB,
  usePerformance,
  getCoreWebVitals,
  useBiometric,
  canUseBiometric,
  getBiometricType,
  useHapticPatterns,
  hapticPatterns,
  contextualHaptics,
  useConnectionQuality,
  isNetworkInformationSupported,
  getConnectionQualityLabel,
  getConnectionQualityColor,
  useWakeLock,
  isWakeLockSupported,
  useIntersectionObserver,
  useLazyLoad,
  useInfiniteScroll,
  useScrollAnimation,
  useViewportTracking,
  isIntersectionObserverSupported,
  useBatteryStatus,
  isBatteryStatusSupported,
  getBatteryIcon,
  getBatteryLevelLabel,
  formatTimeRemaining,
  type WindowSize,
  type CopyToClipboardResult,
  type UseToggleResult,
  type UseOptimisticOptions,
  type OptimisticState,
  type OptimisticActions,
  type ShareData,
  type ShareResult,
  type UseShareReturn,
  type SyncAction,
  type UseBackgroundSyncOptions,
  type UseBackgroundSyncReturn,
  type UseBadgeOptions,
  type UseBadgeReturn,
  type UseIndexedDBOptions,
  type UseIndexedDBReturn,
  type PerformanceMetric,
  type CoreWebVitals,
  type UsePerformanceOptions,
  type UsePerformanceReturn,
  type BiometricCredential,
  type UseBiometricOptions,
  type UseBiometricReturn,
  type HapticSequence,
  type UseHapticPatternsReturn,
  type ConnectionQuality,
  type EffectiveConnectionType,
  type ConnectionInfo,
  type UseConnectionQualityOptions,
  type UseConnectionQualityReturn,
  type UseWakeLockOptions,
  type UseWakeLockReturn,
  type UseIntersectionObserverOptions,
  type UseIntersectionObserverReturn,
  type BatteryStatus,
  type UseBatteryStatusOptions,
  type UseBatteryStatusReturn,
} from './hooks';

// Storage
export {
  IndexedDBStorage,
  getStorage,
  isIndexedDBSupported,
  type StorageOptions,
  type StorageRecord,
} from './utils/storage';

// Utilities
export {
  haptics,
  HapticService,
  useHaptics,
  type HapticPattern,
} from './utils/haptics';

export {
  springConfigs,
  fadeVariants,
  slideUpVariants,
  slideDownVariants,
  scaleVariants,
  scaleBounceVariants,
  slideLeftVariants,
  slideRightVariants,
  buttonPressVariants,
  staggerContainerVariants,
  staggerChildVariants,
  skeletonPulseVariants,
  toastSlideVariants,
  accordionVariants,
  getTransition,
  shouldReduceMotion,
  getAccessibleTransition,
} from './utils/animations';

// Focus Management
export {
  getFocusableElements,
  getFirstFocusable,
  getLastFocusable,
  createFocusTrap,
  FocusManager,
  focusFirstError,
  announce,
  isFocusable,
  moveFocus,
  getFocusOrder,
  disableFocus,
  scrollIntoViewIfNeeded,
  focusAndScroll,
  isFocusWithin,
  RovingTabIndexManager,
} from './utils/focus';
